### ISSUE TITLE
Imagine

### ISSUE THREAD

**Issue by BearMK** [mwalkowiak/CrunchyProfile#3]
When an image is loaded:

Zend\ServiceManager\ServiceManager::createFromInvokable: failed retrieving "crunchyimageservice(alias: crunchy_image_service)" via invokable class "Imagine\Gd\Imagine"; class does not exist

Imagine set...

**Comment by Mr-Negative** [comment]
It is not in description but You need this module: https://github.com/avalanche123/Imagine library in your vendor directory

**Comment by BearMK** [comment]
Thank you, it was my fault...

**Comment by mwalkowiak** [comment]
Mr-Negative: Imagine is in the description, see README file.

2013/6/12 Mr-Negative notifications@github.com

> It is not in description but You need this module:
> https://github.com/avalanche123/Imagine library in your vendor directory
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mwalkowiak/CrunchyProfile/issues/3#issuecomment-19320838
> .

## 

Regards,
Michal Walkowiak
mw@mwalkowiak.com

**Comment by Mr-Negative** [comment]
Oh, I'm sorry, my mistake. Beside that, I found HIS mistake so all good;-)  ps. Really nice module, really useful.
