### ISSUE TITLE
Are there any plans to continue this module?

### ISSUE THREAD

**Issue by ghost** [mwalkowiak/CrunchyProfile#4]
Do you plan to continue the development or do you have stopped working on it?

I need to decide which module to use for a user profile. A possible alternative would be
https://github.com/adamlundrigan/LdcUserProfile/

**Comment by mwalkowiak** [comment]
I would go with the link you mentioned. I did it only for my project and I
have no need for moving forward with it for now.

2014-07-03 1:51 GMT-05:00 Malte Gerth notifications@github.com:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/mwalkowiak/CrunchyProfile/issues/4.

## 

Regards,
Michal Walkowiak
mw@mwalkowiak.com

**Comment by ghost** [comment]
Ok, thanks for the quick response. Maybe you could state this in the Readme file, so any other user could see it.
